cocomo-master/calculator/urls.py
from django.urls import path

from calculator.views import CalculatorView, MainView

app_name = 'calculator'

urlpatterns = [
    path('', MainView.as_view(), name='main'),
    path('calculator/<int:cocomo_version>', CalculatorView.as_view(), name='calculator'),
]

cocomo-master/cocomo/urls.py
# from django.contrib import admin
from django.urls import path, include

app_name = 'cocomo'
urlpatterns = [
    path('', include('calculator.urls'), name='calculator'),
    # path('admin/', admin.site.urls),
]

cocomo-master/calculator/models.py
from django.db import models

# Create your models here.

cocomo-master/calculator/forms.py
from django import forms
from django.core.validators import MinValueValidator
from calculator.calculator import PROJECT_TYPES_BASIC_COCOMO1, PROJECT_TYPES_INTERMEDIATE_COCOMO1, CDS, ESTIMATES, SFS


class BasicCOCOMO1Form(forms.Form):
    project_type = forms.ChoiceField(
        choices=(
            (project_type, project_type)
            for project_type in PROJECT_TYPES_BASIC_COCOMO1.keys()
        ),
        label='Тип проекта'
    )
    size = forms.FloatField(
        label='Объём ПО в тыс. строках кода',
        validators=[MinValueValidator(float(0.001))]
    )

    def clean(self):
        super(BasicCOCOMO1Form, self).clean()

        if not self.cleaned_data.get('size'):
            raise forms.ValidationError(message='Проверьте заполненные данные')


class IntermediateCOCOMO1Form(forms.Form):
    project_type = forms.ChoiceField(
        choices=(
            (project_type, project_type)
            for project_type in PROJECT_TYPES_INTERMEDIATE_COCOMO1.keys()
        ),
        label='Тип проекта'
    )
    size = forms.FloatField(
        label='Объём ПО в тыс. строках кода',
        validators=[MinValueValidator(float(0.001))]
    )

    def __init__(self, *args, **kwargs):
        super(IntermediateCOCOMO1Form, self).__init__(*args, **kwargs)

        for number, data in enumerate(CDS.items(), start=1):
            cd_name, levels = data
            self.fields[f'param_{number}'] = forms.ChoiceField(
                choices=(
                    (param_name, param_name)
                    for param_name in levels.keys()
                ),
                label=f'{number}. {cd_name}',
                initial='средний',
            )

    def clean(self):
        super(IntermediateCOCOMO1Form, self).clean()

        if not self.cleaned_data.get('size'):
            raise forms.ValidationError(message='Проверьте заполненные данные')


class COCOMO2Form(forms.Form):
    size = forms.FloatField(
        label='Объём ПО в тыс. строках кода',
        validators=[MinValueValidator(float(0.001))]
    )

    def __init__(self, *args, **kwargs):
        estimate = kwargs.pop('estimate')
        super(COCOMO2Form, self).__init__(*args, **kwargs)

        start = 1
        for number, data in enumerate(ESTIMATES[estimate].items(), start=start):
            em_name, levels = data
            self.fields[f'em_{number}'] = forms.ChoiceField(
                choices=(
                    (param_name, param_name)
                    for param_name in levels.keys()
                ),
                label=f'{number}. {em_name}',
                initial='средний',
            )
            start += 1

        for number, data in enumerate(SFS.items(), start=start):
            sf_name, levels = data
            self.fields[f'sf_{number}'] = forms.ChoiceField(
                choices=(
                    (param_name, param_name)
                    for param_name in levels.keys()
                ),
                label=f'{number}. {sf_name}',
                initial='средний',
            )


class ResultForm(forms.Form):
    pm = forms.CharField(label='Трудоемкость(PM), чел.× мес')
    pm.widget.attrs['readonly'] = True
    tm = forms.CharField(label='Время разработки(TM), мес')
    tm.widget.attrs['readonly'] = True

    def __init__(self, *args, **kwargs):
        super(ResultForm, self).__init__(*args, **kwargs)

cocomo-master/calculator/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.views.generic.base import View

from calculator.forms import BasicCOCOMO1Form, IntermediateCOCOMO1Form, ResultForm, COCOMO2Form
from calculator.calculator import BasicCOCOMO1, IntermediateCOCOMO1, COCOMO2


class CalculatorView(View):
    def get(self, request, **kwargs):
        session = request.session
        if kwargs.get('cocomo_version') == 1:
            form = BasicCOCOMO1Form(initial=session.get('cocomo_1')) if session.get('cocomo_1') else BasicCOCOMO1Form()
            result_form = ResultForm(initial=session.get('cocomo_1_result')) if session.get('cocomo_1_result') else None
            calculator_name = 'COCOMO (базовый уровень)'

        elif kwargs.get('cocomo_version') == 2:
            form = IntermediateCOCOMO1Form(initial=session.get('cocomo_2')) if session.get(
                'cocomo_2') else IntermediateCOCOMO1Form()
            result_form = ResultForm(initial=session.get('cocomo_2_result')) if session.get('cocomo_2_result') else None
            calculator_name = 'COCOMO (промежуточный уровень)'

        elif kwargs.get('cocomo_version') == 3:
            form = COCOMO2Form(initial=session.get('cocomo_3'), estimate='предварительная') if session.get(
                'cocomo_3') else COCOMO2Form(estimate='предварительная')
            result_form = ResultForm(initial=session.get('cocomo_3_result')) if session.get('cocomo_3_result') else None
            calculator_name = 'COCOMO II (предварительная оценка)'

        elif kwargs.get('cocomo_version') == 4:
            form = COCOMO2Form(initial=session.get('cocomo_4'), estimate='детальная') if session.get(
                'cocomo_4') else COCOMO2Form(estimate='детальная')
            result_form = ResultForm(initial=session.get('cocomo_4_result')) if session.get('cocomo_4_result') else None
            calculator_name = 'COCOMO II (детальная оценка)'

        else:
            return HttpResponseRedirect(reverse('calculator:main'))

        context = {
            'form': form,
            'result_form': result_form,
            'calculator_name': calculator_name,
        }
        return render(request, 'calculator/calculator.html', context)

    def post(self, request, **kwargs):
        if kwargs.get('cocomo_version') == 1:
            calculator_name = 'COCOMO (базовый уровень)'
            form = BasicCOCOMO1Form(request.POST)

            if form.is_valid():
                result = BasicCOCOMO1(
                    project_type=form.cleaned_data.get('project_type'),
                    size=form.cleaned_data.get('size'),
                )
                result_form = ResultForm(initial={'pm': str(result.pm), 'tm': str(result.tm)})

                request.session['cocomo_1'] = request.POST
                request.session['cocomo_1_result'] = {'pm': str(result.pm), 'tm': str(result.tm)}

                context = {
                    'result_form': result_form,
                    'form': form,
                    'calculator_name': calculator_name,
                }
                return render(request, 'calculator/calculator.html', context)

            context = {
                'form': form,
                'calculator_name': calculator_name,
            }
            return render(request, 'calculator/calculator.html', context)

        elif kwargs.get('cocomo_version') == 2:
            calculator_name = 'COCOMO (промежуточный уровень)'
            form = IntermediateCOCOMO1Form(request.POST)

            if form.is_valid():
                result = IntermediateCOCOMO1(
                    project_type=form.cleaned_data.get('project_type'),
                    size=form.cleaned_data.get('size'),
                    cds=[
                        form.cleaned_data[param_name]
                        for param_name in form.cleaned_data.keys()
                        if 'param' in param_name
                    ]
                )
                result_form = ResultForm(initial={'pm': str(result.pm), 'tm': str(result.tm)})

                request.session['cocomo_2'] = request.POST
                request.session['cocomo_2_result'] = {'pm': str(result.pm), 'tm': str(result.tm)}

                context = {
                    'result_form': result_form,
                    'form': form,
                    'calculator_name': calculator_name,
                }
                return render(request, 'calculator/calculator.html', context)

            context = {
                'form': form,
                'calculator_name': calculator_name,
            }
            return render(request, 'calculator/calculator.html', context)

        elif kwargs.get('cocomo_version') == 3:
            calculator_name = 'COCOMO II (предварительная оценка)'
            form = COCOMO2Form(request.POST, estimate='предварительная')

            if form.is_valid():
                result = COCOMO2(
                    ems=[
                        form.cleaned_data[param_name]
                        for param_name in form.cleaned_data.keys()
                        if 'em' in param_name
                    ],
                    sfs=[
                        form.cleaned_data[param_name]
                        for param_name in form.cleaned_data.keys()
                        if 'sf' in param_name
                    ],
                    size=form.cleaned_data.get('size'),
                    estimate='предварительная',
                )
                result_form = ResultForm(initial={'pm': str(result.pm), 'tm': str(result.tm)})

                request.session['cocomo_3'] = request.POST
                request.session['cocomo_3_result'] = {'pm': str(result.pm), 'tm': str(result.tm)}

                context = {
                    'result_form': result_form,
                    'form': form,
                    'calculator_name': calculator_name,
                }
                return render(request, 'calculator/calculator.html', context)

            context = {
                'form': form,
                'calculator_name': calculator_name,
            }
            return render(request, 'calculator/calculator.html', context)

        elif kwargs.get('cocomo_version') == 4:
            calculator_name = 'COCOMO II (детальная оценка)'
            form = COCOMO2Form(request.POST, estimate='детальная')

            if form.is_valid():
                result = COCOMO2(
                    ems=[
                        form.cleaned_data[param_name]
                        for param_name in form.cleaned_data.keys()
                        if 'em' in param_name
                    ],
                    sfs=[
                        form.cleaned_data[param_name]
                        for param_name in form.cleaned_data.keys()
                        if 'sf' in param_name
                    ],
                    size=form.cleaned_data.get('size'),
                    estimate='детальная',
                )
                result_form = ResultForm(initial={'pm': str(result.pm), 'tm': str(result.tm)})

                request.session['cocomo_4'] = request.POST
                request.session['cocomo_4_result'] = {'pm': str(result.pm), 'tm': str(result.tm)}

                context = {
                    'result_form': result_form,
                    'form': form,
                    'calculator_name': calculator_name,
                }
                return render(request, 'calculator/calculator.html', context)

            context = {
                'form': form,
                'calculator_name': calculator_name,
            }
            return render(request, 'calculator/calculator.html', context)

        else:
            return HttpResponseRedirect(reverse('calculator:main'))


class MainView(View):
    def get(self, request, *_, **__):
        return render(request, 'calculator/main.html')

cocomo-master/calculator/templates/calculator/base.html
{% load static %}
<head>
    <meta charset="UTF-8">
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    {% block head %}{% endblock %}
</head>
<body>
<div id="wrapper">
    <div id="content">
        <div class="menu">
            <div class="container-fluid">
                <div class="navbar-header">
                    <a href="{% url 'calculator:main' %}">Описание</a>
                </div>
                <div>
                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="{% url 'calculator:calculator' cocomo_version=1 %}">
                            <span class="glyphicon glyphicon-asterisk"></span>
                            COCOMO(базовый ур.)</a></li>
                        <li><a href="{% url 'calculator:calculator' cocomo_version=2 %}">
                            <span class="glyphicon glyphicon-asterisk"></span>
                            COCOMO(промежуточный ур.)</a></li>
                        <li><a href="{% url 'calculator:calculator' cocomo_version=3 %}">
                            <span class="glyphicon glyphicon-asterisk"></span>
                            COCOMOII(предварительная оценка)</a></li>
                        <li><a href="{% url 'calculator:calculator' cocomo_version=4 %}">
                            <span class="glyphicon glyphicon-asterisk"></span>
                            COCOMOII(детальная оценка)</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    {% block content %}{% endblock %}
    <footer class="card-footer">
        <p><span class="glyphicon glyphicon-copyright-mark"> В.Р.Силюк, 2022</span>
        </p>
    </footer>
</div>
</div>
</body>

cocomo-master/calculator/templates/calculator/calculator.html
{% extends 'calculator/base.html' %}
{% load bootstrap %}
{% block head %}
<title>Калькулятор COCOMO</title>
{% endblock %}
{% block content %}
<body>
<div class="container">
    {% if result_form %}
    <div class="row">
        <h4>Результаты</h4>
        <div class="panel panel-primary">
            <div class="panel-heading"></div>
            <div class="panel-body">
                <form action="" method="post">
                    {% csrf_token %}
                    {{ result_form|bootstrap }}
                </form>
            </div>
        </div>
    </div>
    {% endif %}
    <div class="row">
        <h4>{{ calculator_name }}</h4>
        <div class="panel panel-primary">
            <div class="panel-heading"></div>
            <div class="panel-body">
                <form action="" method="post">
                    {% csrf_token %}
                    {% if calculator_name == 'COCOMO (базовый уровень)' %}
                        <h3><center>Типы проекта</center></h3>
                        <p>1. Распространенный тип (organic projects) характеризуется тем, что проект выполняется небольшой группой специалистов, имеющих опыт в создании подобных изделий и
опыт применения технологических средств. Условия работы стабильны, и изделие имеет
относительно невысокую сложность. </p>
                        <p>2. Встроенный тип (embedded projects) характеризуется очень жесткими требованиями
на программный продукт, интерфейсы, параметры ЭВМ. Как правило, у таких изделий
высокая степень новизны и планирование работ осуществляется при недостаточной информации, как о самом изделии, так и об условиях работы. Встроенный проект требует
больших затрат на изменения и исправления. </p>
                        <p>3. Полунезависимый тип (semidetached projects) занимает промежуточное положение
между распространенным и встроенным – это проекты средней сложности. Исполнители
знакомы лишь с некоторыми характеристиками (или компонентами) создаваемой системы, имеют средний опыт работы с подобными изделиями, изделие имеет элемент новизны. Только часть требований к изделию жестко фиксируется, в остальном разработки
имеют степени выбора.</p>
                    {{ form|bootstrap }}
                    {% elif calculator_name == 'COCOMO (промежуточный уровень)' %}
                        <h3><center>Типы проекта</center></h3>
                        <p>1. Распространенный тип (organic projects) характеризуется тем, что проект выполняется небольшой группой специалистов, имеющих опыт в создании подобных изделий и
опыт применения технологических средств. Условия работы стабильны, и изделие имеет
относительно невысокую сложность. </p>
                        <p>2. Встроенный тип (embedded projects) характеризуется очень жесткими требованиями
на программный продукт, интерфейсы, параметры ЭВМ. Как правило, у таких изделий
высокая степень новизны и планирование работ осуществляется при недостаточной информации, как о самом изделии, так и об условиях работы. Встроенный проект требует
больших затрат на изменения и исправления. </p>
                        <p>3. Полунезависимый тип (semidetached projects) занимает промежуточное положение
между распространенным и встроенным – это проекты средней сложности. Исполнители
знакомы лишь с некоторыми характеристиками (или компонентами) создаваемой системы, имеют средний опыт работы с подобными изделиями, изделие имеет элемент новизны. Только часть требований к изделию жестко фиксируется, в остальном разработки
имеют степени выбора.</p>
                    {{ form.project_type|bootstrap }}
                    {{ form.size|bootstrap }}
                    <h4>Характеристики продукта</h4>
                    {{ form.param_1|bootstrap }}
                    {{ form.param_2|bootstrap }}
                    {{ form.param_3|bootstrap }}
                    <h4>Характеристики аппаратного обеспечения</h4>
                    {{ form.param_4|bootstrap }}
                    {{ form.param_5|bootstrap }}
                    {{ form.param_6|bootstrap }}
                    {{ form.param_7|bootstrap }}
                    <h4>Характеристики персонала</h4>
                    {{ form.param_8|bootstrap }}
                    {{ form.param_9|bootstrap }}
                    {{ form.param_10|bootstrap }}
                    {{ form.param_11|bootstrap }}
                    {{ form.param_12|bootstrap }}
                    <h4>Характеристики проекта</h4>
                    {{ form.param_13|bootstrap }}
                    {{ form.param_14|bootstrap }}
                    {{ form.param_15|bootstrap }}
                    {% elif calculator_name == 'COCOMO II (предварительная оценка)' %}
                    {{ form.size|bootstrap }}
                    <h4>Параметры персонала</h4>
                    {{ form.em_1|bootstrap }}
                    {{ form.em_2|bootstrap }}
                    <h4>Параметры продукта</h4>
                    {{ form.em_3|bootstrap }}
                    {{ form.em_4|bootstrap }}
                    <h4>Параметры платформы</h4>
                    {{ form.em_5|bootstrap }}
                    <h4>Параметры проекта</h4>
                    {{ form.em_6|bootstrap }}
                    {{ form.em_7|bootstrap }}
                    <h4>Факторы масштаба</h4>
                    {{ form.sf_8|bootstrap }}
                    {{ form.sf_9|bootstrap }}
                    {{ form.sf_10|bootstrap }}
                    {{ form.sf_11|bootstrap }}
                    {{ form.sf_12|bootstrap }}
                    {% elif calculator_name == 'COCOMO II (детальная оценка)' %}
                    {{ form.size|bootstrap }}
                    <h4>Параметры персонала</h4>
                    {{ form.em_1|bootstrap }}
                    {{ form.em_2|bootstrap }}
                    {{ form.em_3|bootstrap }}
                    {{ form.em_4|bootstrap }}
                    {{ form.em_5|bootstrap }}
                    {{ form.em_6|bootstrap }}
                    <h4>Параметры продукта</h4>
                    {{ form.em_7|bootstrap }}
                    {{ form.em_8|bootstrap }}
                    {{ form.em_9|bootstrap }}
                    {{ form.em_10|bootstrap }}
                    {{ form.em_11|bootstrap }}
                    <h4>Параметры платформы</h4>
                    {{ form.em_12|bootstrap }}
                    {{ form.em_13|bootstrap }}
                    {{ form.em_14|bootstrap }}
                    <h4>Параметры проекта</h4>
                    {{ form.em_15|bootstrap }}
                    {{ form.em_16|bootstrap }}
                    {{ form.em_17|bootstrap }}
                    <h4>Факторы масштаба</h4>
                    {{ form.sf_18|bootstrap }}
                    {{ form.sf_19|bootstrap }}
                    {{ form.sf_20|bootstrap }}
                    {{ form.sf_21|bootstrap }}
                    {{ form.sf_22|bootstrap }}
                    {% endif %}
                    <button class="btn btn-primary pull-center"
                            type="submit">Расчёт
                    </button>
                </form>
            </div>
        </div>
    </div>
</div>
</body>
{% endblock %}